import { readFileSync } from "node:fs";
import { join } from "node:path";
import { XMLParser } from "fast-xml-parser";
import type { NewsItem, ProcessedNewsItem } from "./types";

// ---------------------------------------------------------------------------
// Static processed news (generated by scripts/fetch-news.mjs)
// ---------------------------------------------------------------------------
let _processedCache: ProcessedNewsItem[] | null = null;

function getProcessedNews(): ProcessedNewsItem[] {
  if (_processedCache) return _processedCache;
  try {
    const raw = readFileSync(join(process.cwd(), "src", "data", "noticias.json"), "utf-8");
    _processedCache = JSON.parse(raw);
  } catch {
    _processedCache = [];
  }
  return _processedCache;
}

export function getProcessedNewsList(limit = 30): ProcessedNewsItem[] {
  return getProcessedNews().slice(0, limit);
}

export function getProcessedNewsBySlug(slug: string): ProcessedNewsItem | undefined {
  return getProcessedNews().find((n) => n.slug === slug);
}

export function getProcessedNewsByTeam(team: string, limit = 20): ProcessedNewsItem[] {
  return getProcessedNews().filter((n) => n.team === team).slice(0, limit);
}

// ---------------------------------------------------------------------------
// Live RSS fallback (used when no processed news available)
// ---------------------------------------------------------------------------
const FEEDS = [
  { name: "Motorsport.com ES", url: "https://es.motorsport.com/rss/f1/news/" },
  { name: "Motorsport.com LAT", url: "https://lat.motorsport.com/rss/f1/news/" },
];

const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: "@_" });

async function fetchFeed(url: string): Promise<NewsItem[] | null> {
  try {
    const res = await fetch(url, {
      headers: { accept: "application/rss+xml, application/xml, text/xml" },
    });
    if (!res.ok) return null;
    const text = await res.text();
    const doc = parser.parse(text);
    const items = doc.rss?.channel?.item ?? doc.feed?.entry ?? [];
    if (!Array.isArray(items)) return [];
    return items
      .map((item: { title?: string; link?: string; pubDate?: string; description?: string; enclosure?: { "@_url"?: string } }) => {
        const title = typeof item.title === "string" ? item.title.trim() : "";
        const link = typeof item.link === "string" ? item.link.trim() : "";
        if (!title || !link) return null;
        const pub = item.pubDate ? new Date(item.pubDate) : null;
        const rawDesc = typeof item.description === "string" ? item.description : "";
        return {
          title,
          link,
          source: "",
          date: pub && !Number.isNaN(pub.getTime()) ? pub.toISOString() : null,
          description: rawDesc
            .replace(/<!\[CDATA\[|\]\]>/g, "")
            .replace(/<[^>]*>/g, " ")
            .replace(/\s+/g, " ")
            .trim()
            .slice(0, 200),
          imageUrl: item.enclosure?.["@_url"] || null,
        } as NewsItem;
      })
      .filter((item: NewsItem | null): item is NewsItem => item !== null);
  } catch {
    return null;
  }
}

async function fetchLiveNews(limit = 30): Promise<NewsItem[]> {
  const sources = await Promise.all(
    FEEDS.map(async (feed) => {
      const items = await fetchFeed(feed.url);
      return (items ?? []).map((item) => ({ ...item, source: feed.name }));
    }),
  );

  const seen = new Set<string>();
  const merged: NewsItem[] = [];
  for (const item of sources.flat()) {
    const key = item.title.toLowerCase().slice(0, 80);
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(item);
  }

  return merged
    .sort((a, b) => {
      const da = a.date ? new Date(a.date).getTime() : 0;
      const db = b.date ? new Date(b.date).getTime() : 0;
      return db - da;
    })
    .slice(0, limit);
}

// ---------------------------------------------------------------------------
// Unified getter: prefers processed news, falls back to live RSS
// ---------------------------------------------------------------------------
export async function getNews(limit = 30): Promise<NewsItem[]> {
  const processed = getProcessedNewsList(limit);
  if (processed.length > 0) {
    return processed.map((p) => ({
      title: p.title,
      link: `/noticias/${p.slug}`,
      source: p.source,
      date: p.date,
      description: p.summary,
      imageUrl: p.teamImage,
    }));
  }
  return fetchLiveNews(limit);
}
